// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNF0acFUr34Pl_pyaMcPW5t6DcvAeJy9E',
    appId: '1:1071363025152:web:c3979c7c68f75d02df6be5',
    messagingSenderId: '1071363025152',
    projectId: 'my-halaqoh',
    authDomain: 'my-halaqoh.firebaseapp.com',
    storageBucket: 'my-halaqoh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa6VDj-MPI4mhVF78gn0AOnF1mA5uwwZk',
    appId: '1:1071363025152:android:c88c52a6741537ebdf6be5',
    messagingSenderId: '1071363025152',
    projectId: 'my-halaqoh',
    storageBucket: 'my-halaqoh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcapPF0_Szb8nHt8H8iRHBN31ozafj-q4',
    appId: '1:1071363025152:ios:cc28a086a6875950df6be5',
    messagingSenderId: '1071363025152',
    projectId: 'my-halaqoh',
    storageBucket: 'my-halaqoh.firebasestorage.app',
    iosBundleId: 'com.luqmanalhakim.surabaya.myHalaqoh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcapPF0_Szb8nHt8H8iRHBN31ozafj-q4',
    appId: '1:1071363025152:ios:cc28a086a6875950df6be5',
    messagingSenderId: '1071363025152',
    projectId: 'my-halaqoh',
    storageBucket: 'my-halaqoh.firebasestorage.app',
    iosBundleId: 'com.luqmanalhakim.surabaya.myHalaqoh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNF0acFUr34Pl_pyaMcPW5t6DcvAeJy9E',
    appId: '1:1071363025152:web:aba0ac5b30c132b7df6be5',
    messagingSenderId: '1071363025152',
    projectId: 'my-halaqoh',
    authDomain: 'my-halaqoh.firebaseapp.com',
    storageBucket: 'my-halaqoh.firebasestorage.app',
  );
}
